# webapps-all.yaml
---
# 1) Namespaces
apiVersion: v1
kind: Namespace
metadata:
  name: webapp1
---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp2

---
# 2) webapp1 (in namespace webapp1)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-deployment
  namespace: webapp1
  labels:
    app: webapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
        - name: echoserver
          image: gcr.io/google_containers/echoserver:1.10
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp1-service
  namespace: webapp1
spec:
  type: ClusterIP
  selector:
    app: webapp1
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp1-ingress
  namespace: webapp1
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: webapp1.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp1-service
                port:
                  number: 80

---
# 3) webapp2 (in namespace webapp2)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-deployment
  namespace: webapp2
  labels:
    app: webapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp2
  template:
    metadata:
      labels:
        app: webapp2
    spec:
      containers:
        - name: echoserver
          image: gcr.io/google_containers/echoserver:1.10
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp2-service
  namespace: webapp2
spec:
  type: ClusterIP
  selector:
    app: webapp2
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp2-ingress
  namespace: webapp2
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: webapp2.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp2-service
                port:
                  number: 80
